### ISSUE TITLE
Tổ chức thư mục cho ghichep-nagios

### ISSUE THREAD

**Issue by congto** [meditechopen/meditech-ghichep-nagios#3]
@hoangdh 
Em tổ chức thư mục như sau
- docs: chứa các tài liệu về cấu trúc, thành phần
--- file tài liệu về kiến trúc, thành phần, các trick hay ghi chép cần chú ý
--- file tài liệu về lab, hướng dẫn cài đặt
- tools or script: chứa các script cài đặt
- images: chứa các hình ảnh
- File `readme.md` ngoài cùng: chứa mục lục để link đến tài liệu.

Cơ cấu lại nhé.

**Comment by hoangdh** [comment]
@congto 

Em quên mất thư mục docs :) Để em làm lại ngay a ạ!

**Comment by congto** [comment]
@hoangdh làm lại các y.c này chưa em?
