### ISSUE TITLE
bổ sung file ảnh mô hình và file ip planning để lab

### ISSUE THREAD

**Issue by congto** [meditechopen/meditech-ghichep-nagios#8]
@hoangdh em bổ sung
1. file ảnh về mô hình
2. file excel và chụp ảnh các ip trong mô hình lab. 

Lấy file excel ở đây, file hình tự vẽ https://github.com/congto/ghichep-CEPH/tree/master/tools

**Comment by hoangdh** [comment]
Hi a @congto 

- Phần mô hình thì em vẽ như thế này, không biết đã đúng ý anh chưa: http://prntscr.com/en0iu4
(Phần này em vẽ mô hình LAB Nagios để giám sát 3 dịch vụ MySQL, Web, RabbitMQ)
- File excel: http://prntscr.com/en0rgf (Cấu hình em lab)

**Comment by congto** [comment]
Hi @hoangdh 

Chỉnh sửa theo mẫu anh gửi, em nên làm lên google excel ấy, tiện dùng lại sau này.

**Comment by congto** [comment]
@hoangdh @trimq Các bài viết hướng dẫn cài đặt anh chưa thấy update mô hình. Các em cập nhật lại nhé.

Ngoài ra, thư mục script mà Trí up lên thì vứt sang phần tools đi nhé. Các script mình viết để hết ở đó @hoangdh và @trimq  nhé.

**Comment by trimq** [comment]
@congto em cập nhật lại rồi anh
